application: wechat-rent
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico

- url: /assets
  static_dir: assets

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: lxml 
  version: latest
- name: yaml
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1 # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50
